
enum Enums { 
    TIN = "T",
	INTERNAL_INITIATIVE = "II",
	VALUE_COMPLEXITY = "VC",
	HIGHEST_VALUE = "HV",
	LOWEST_COMPLEXITY = "LC",
	LEVELSET_TEAM_ORG = "LT",
	DISTANCE_TO_DESIRED_MATURITY = "DTM",
	NO_ACTION_TARGET_MATURITY_REACHED = "NAT",
	NO_ACTION_OTHER = "NAO" 
  }
